# theme docs https://squidfunk.github.io/mkdocs-material/getting-started/

site_name: grGWAS docs
site_url: https://maf-grls.github.io/grGWAS/
repo_name: MAF-GRLS/grGWAS
repo_url: https://github.com/MAF-GRLS/grGWAS
edit_uri: tree/main/docs/


theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  
      
  features:
    - content.code.copy
    - content.code.annotate
    - content.action.view
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - search.highlight
    - content.tabs.link



nav:
  - Home: index.md
  - Tutorial:
    - 1. Environment Setup: 1.install.md
    - 2. Input Description: 2.Input_files.md
    - 3. Prep Array Sets: 3.prep_arrays.md
    - 4. QC & filtration: 4.qc_filter.md
    - 5. Study design: 5.pheno.md
    - 6. Heritability: 6.heritability.md
    - 7. GWAS Analysis: 7.gwas.md
  - Bulletin:
    - Health concerns: ext_docs/health_concerns.md
    - Previous GWAS: ext_docs/gwas_studies.md
    - Sample-distance: ext_docs/sample_distance.md
    - Admixture analysis: ext_docs/admixture_analysis.md
    - GREML analysis: ext_docs/GREML_analysis.md
  

  # - Examples:
  #   - Example 1: DisGeNET_similarity_network-complete.ipynb
  #   - Example 2: example2.md

plugins:
  - search
  # - mkdocs-jupyter
  # - git-authors
  # - git-revision-date-localized:
  #     enable_creation_date: true
  - glightbox:
      zoomable: true
      slide_effect: slide
      draggable: true
      caption_position: bottom

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true

